services:

  backend:
    build: ./Backend-ropa
    container_name: backend-ropa

    ports:
      - "5000:5000"

    volumes:
      - ./Backend-ropa:/app
      - /app/node_modules

    env_file:
      - ./Backend-ropa/.env

  frontend:
    build: ./Frontend
    container_name: frontend-react

    ports:
      - "3000:3000"

    volumes:
      - ./Frontend:/app
      - /app/node_modules

    stdin_open: true
    tty: true

    depends_on:
      - backend